# SPDX-FileCopyrightText: Contributors to PyPSA-Earth
# SPDX-FileCopyrightText: Open Energy Transition gGmbH
# SPDX-License-Identifier: CC0-1.0
# Scenario diff — 2040 planning horizon
# Merges with: configs/cap_exp_zambia_base.yaml

run:
  name: cap_exp_zambia_2040
  base_config: configs/cap_exp_zambia_base.yaml

electricity:
  powerplants_filter: (DateOut >= 2040 or DateOut != DateOut) and (DateIn <= 2040 or DateIn != DateIn)
  extendable_carriers:
    Generator: [solar, onwind]

load_options:
  scale: 3.75  # IRP Table 3 2040 demand 59,674 GWh / DemandCast base 15,909 GWh

costs:
  year: 2040
