# SPDX-FileCopyrightText: Contributors to PyPSA-Earth
# SPDX-FileCopyrightText: Open Energy Transition gGmbH
# SPDX-License-Identifier: CC0-1.0
# Scenario diff — 2030 planning horizon
# Merges with: configs/cap_exp_zambia_base.yaml

run:
  name: cap_exp_zambia_2030
  base_config: configs/cap_exp_zambia_base.yaml

electricity:
  powerplants_filter: (DateOut >= 2030 or DateOut != DateOut) and (DateIn <= 2030 or DateIn != DateIn)
  extendable_carriers:
    Generator: [solar, onwind, ror]

load_options:
  scale: 2.10

costs:
  year: 2030
  marginal_cost:
    coal: 79.92
    oil: 4.70
