# SPDX-FileCopyrightText: Contributors to PyPSA-Earth
# SPDX-FileCopyrightText: Open Energy Transition gGmbH
# SPDX-License-Identifier: CC0-1.0
# Scenario diff — 2023 planning horizon
# Merges with: configs/cap_exp_zambia_base.yaml

run:
  name: config.zm.valid_2023
  base_config: configs/zambia_configs/config.zm.validation_dispatch.yaml

snapshots:
  start: '2023-01-01'
  end: '2024-01-01'
  inclusive: left   # end is not inclusive
countries: [ZM]

scenario:
  simpl: ['']
  ll: [v1.0]
  clusters: ['10']
  opts: [Co2L-3h]

atlite:
  nprocesses: 4
  default: zm-2023-era5
  hydro: hydro/zm-2023-glofas.nc

electricity:
  powerplants_filter: (DateOut >= 2023 or DateOut != DateOut) and (DateIn <= 2023 or DateIn != DateIn)
  extendable_carriers:
    Generator: []

lines:
  s_max_pu: 0.70

renewable:
  hydro:
    source: custom
    multiplier: 0.175

load_options:
  source: demcast
  weather_year: 2023
  scale: 1.25

costs:
  year: 2020

validation:
  interconnectors:
    enable: true
